schema = {
    "background": "Background Color",
    "black": "Ansi 0 Color",
    "blue": "Ansi 4 Color",
    "brightBlack": "Ansi 8 Color",
    "brightBlue": "Ansi 12 Color",
    "brightCyan": "Ansi 14 Color",
    "brightGreen": "Ansi 10 Color",
    "brightPurple": "Ansi 13 Color",
    "brightRed": "Ansi 9 Color",
    "brightWhite": "Ansi 15 Color",
    "brightYellow": "Ansi 11 Color",
    "cursorColor": "Cursor Color",
    "cyan": "Ansi 6 Color",
    "foreground": "Foreground Color",
    "green": "Ansi 2 Color",
    "purple": "Ansi 5 Color",
    "red": "Ansi 1 Color",
    "selectionBackground": "Selection Color",
    "white": "Ansi 7 Color",
    "yellow": "Ansi 3 Color",
    "name": None,
}
